### ISSUE TITLE
Collaboration 

### ISSUE THREAD

**Issue by saltsoftdrink** [arlbibek/windows-ahk#11]
Hey Buddy, Can I also work on this project cuz I've tons of ideas & tricks on this project. I've spent hours & hours to try something cool with AHK. So, all my knowledge I can put in it. 

I will be glad to listen that, what your thoughts on it.

Plz give me any social handle where we can talk cuz GitHub is not a chatting platform.

Hope there will be a Good AHK tastes to people.

Let's Goo!

**Comment by arlbibek** [comment]
**Sure, I'd love that.** Let's connect on the discord channel at [discord. gg/a2NyrV6PBY](https://discord.gg/a2NyrV6PBY) and discuss this further. Alternatively, you can reach to me via email at contact@bibeka.com.np.
Looking forward to working together. ✌️
