### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by saltsoftdrink** [arlbibek/windows-ahk#2]
You can also add Advanced Windows Snapping by ahk. Add this in this script

**Comment by arlbibek** [comment]
Hi, is it possible that you to provide a link to what you are referring to?

**Comment by saltsoftdrink** [comment]
I've Found 2, But work on it

1. https://bl.ocks.org/park-brian/f3f790e559e5145b99bf0f19c7928dd8
2. https://gist.github.com/AWMooreCO/1ef708055a11862ca9dc

**Comment by arlbibek** [comment]
Sure, I'll look into it and see what I can do. ;)

**Comment by arlbibek** [comment]
Hello @Samyak-Bumb, as suggested I've added [Advanced Window Snap](https://github.com/arlbibek/windows-ahk#advanced-window-snap-dacios-fork) ([Dacio's Fork](https://gist.github.com/dacioromero/b25c3a782b29bfc783b36804324fd780)). 

_I've added the script as it is as I'm not sure what to make changes of._
