### ISSUE TITLE
Reference to specific user

### ISSUE THREAD

**Issue by JaredCH** [arlbibek/windows-ahk#3]
Line#59, change to `Run, %AppData%\Microsoft\Windows\Start Menu\Programs\Startup`

from
```
visit_startup(){
    Run, C:\Users\bibek\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
}
```

**Comment by arlbibek** [comment]
Hi, this has been updated in [dev](https://github.com/arlbibek/windows-ahk/tree/dev) and will be updated accordingly. See [Removed visit_startup() as it was unnecessary](https://github.com/arlbibek/windows-ahk/commit/549b6b337eba68fd1d4ee5c2892a9e7f84d2ca4a). 
Thank you for bringing this to light!
